on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"   # every hour at minute 0
  workflow_dispatch:

jobs:
  ftp-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: defaultcreds.lol

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if new commits since last run
        id: changes
        run: |
          if git log -1 --since="1 hour ago" --oneline | grep .; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in the last hour. Skipping deploy."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to FTP server
        if: steps.changes.outputs.has_changes == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
