name: Deploy via FTP

on:
  push:
    branches:
      - main   # Or your deployment branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: SamKirkland/FTP-Deploy-Action@v30

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /  # Update as needed
